name: Code quality

on:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Run Linter/Formatter
        run: npm run lint
