name: Code quality

on:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install packages
        run: bun install

      - name: Check Prettier formatting
        run: prettier --check "**/*.{md,mdx,astro}"

      - name: Run ESLint
        run: eslint "src/**/*.{astro,}"

      - name: Check Biome configuration
        run: npx @biomejs/biome check ./
